version: "3.9"

services:
  redis:
    image: "redis:alpine"

    command: redis-server --requirepass <PASSWORD>

    ports:
      - "6379:6379"

    volumes:
      - $PWD/redis-data:/var/lib/redis

    environment:
      - REDIS_REPLICATION_MODE=master

  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      - REDIS_REPLICATION_MODE=master
    depends_on:
      - redis