# Generated by Django 4.0 on 2021-12-16 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crypto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=300)),
                ('score', models.IntegerField()),
                ('date', models.DateField()),
                ('crypto_currency', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='crypto.currency')),
            ],
        ),
        migrations.CreateModel(
            name='SentimentScores',
            fields=[
                ('post', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='reddit.posts')),
                ('sentiment_score', models.FloatField()),
            ],
        ),
    ]
