# Generated by Django 4.0 on 2021-12-21 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0005_alter_currencies_rank'),
        ('reddit', '0003_remove_posts_crypto_currency_posts_crypto_currency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='crypto_currency',
        ),
        migrations.AddField(
            model_name='posts',
            name='crypto_currency',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='crypto.currencies'),
            preserve_default=False,
        ),
    ]
