# Generated by Django 4.0 on 2021-12-21 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reddit', '0004_remove_posts_crypto_currency_posts_crypto_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='text',
            field=models.CharField(max_length=5000),
        ),
    ]
