# Generated by Django 4.0 on 2021-12-16 13:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=4, unique=True)),
                ('slug', models.CharField(max_length=20, unique=True)),
                ('rank', models.IntegerField()),
                ('active_top', models.BooleanField(default=True)),
                ('last_changed', models.DateField(default=datetime.date.today)),
            ],
        ),
    ]
