# Generated by Django 4.0 on 2021-12-16 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reddit', '0001_initial'),
        ('crypto', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Currency',
            new_name='Currencies',
        ),
    ]
