# Generated by Django 4.0 on 2021-12-16 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0002_rename_currency_currencies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currencies',
            name='active_top',
            field=models.BooleanField(auto_created=True),
        ),
        migrations.AlterField(
            model_name='currencies',
            name='last_changed',
            field=models.DateField(auto_now_add=True),
        ),
    ]
