# Generated by Django 4.0 on 2021-12-16 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0003_alter_currencies_active_top_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currencies',
            name='slug',
            field=models.CharField(max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='currencies',
            name='symbol',
            field=models.CharField(max_length=5, unique=True),
        ),
    ]
