# Generated by Django 4.0 on 2021-12-22 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0007_analysedscores_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysedscores',
            name='score',
            field=models.FloatField(),
        ),
    ]
