# Generated by Django 4.0 on 2021-12-24 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0008_alter_analysedscores_score'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='analysedscores',
            options={'managed': False},
        ),
    ]
