# Generated by Django 4.0 on 2021-12-24 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0011_analysedscoresmaterializedview_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AnalysedScores',
        ),
    ]
