# Generated by Django 4.0 on 2021-12-25 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0012_delete_analysedscores'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='analysedscoresmaterializedview',
            options={},
        ),
    ]
