# Generated by Django 4.0 on 2021-12-25 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0013_alter_analysedscoresmaterializedview_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysedscoresmaterializedview',
            name='crypto_currency',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='crypto.currencies'),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='analysedscoresmaterializedview',
            table=None,
        ),
    ]
