# Generated by Django 4.0 on 2021-12-25 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0014_analysedscoresmaterializedview_crypto_currency_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AnalysedScoresMaterializedView',
            new_name='AnalysedScores',
        ),
    ]
