# Generated by Django 4.0 on 2021-12-25 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0015_rename_analysedscoresmaterializedview_analysedscores'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewAnalysedScores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('score', models.FloatField()),
                ('crypto_currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crypto.currencies')),
            ],
        ),
        migrations.DeleteModel(
            name='AnalysedScores',
        ),
    ]
