# Generated by Django 4.0 on 2021-12-25 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0017_analysedscores_delete_newanalysedscores'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='analysedscores',
            options={'managed': True},
        ),
    ]
