# Generated by Django 4.0 on 2021-12-25 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0018_alter_analysedscores_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='analysedscores',
            options={'managed': False},
        ),
    ]
